apiVersion: v1
kind: Namespace
metadata:
  name: adot-col3
  labels:
    name: adot-col3

---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  namespace: adot-col3
  labels:
    app: my-nginx-app
spec:
  selector:
    app: my-nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: adot-col3
  labels:
    app: my-nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-app
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      containers:
      - name: my-nginx-container-100
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 200Mi